<?php

require_once 'mailer/mailer/class.phpmailer.php'; 
  $mail = new PHPMailer(true); 
 $emailid='amcpc@ecil.co.in';
 $pwd = 'Amcpc@2734';
  // $email   = strip_tags($_POST['mailid']);
   $subject = "Complaint Closed";



session_start();  
    if(!isset($_SESSION["sess_user"]))
	{  
        //header("location:purchase.php"); 

		
    } 
	else 
	{
		print " User Type: ".$_SESSION["userType"]."<BR>";
		echo " User Name: ".$_SESSION["sess_user"];
	}
	
	
	   $con=mysqli_connect('localhost','root','Naveen@798@@') or die(mysql_error());  
     	mysqli_select_db($con,'amc') or die("cannot select DB"); 
   
    $sql3 = "SELECT * FROM `adminmail`";
     $result3=mysqli_query($con,$sql3);
     $numrows3=mysqli_num_rows($result3); 
	
		 if($numrows3==0)
		 {
	//	 echo "No data exist in the workpack_contact table";	 
		 }
		 else
		 { 
			while($row3=mysqli_fetch_assoc($result3)) 
				{
				$sendermailid= $row3['Mail_ID'];	
                $senderpassword= $row3['Password'];		
				}
		 }
   
   
     mysqli_close($con);
	
	
	
	
	
	
	
	
	$con=mysqli_connect('localhost','root','Naveen@798@@') or die(mysql_error());  
    mysqli_select_db($con,'pcamc') or die("cannot select DB");  
	
	
	
	
	
	$sernum= $_POST['sernum'];
	$comp_Sts= $_POST['cursts'];
	//$mailid = $_POST['mailid'];
	
	
	$qry = "SELECT * FROM complaint where serialNumber ='".$sernum."'";
    $result1=mysqli_query($con,$qry);
    $numrows1=mysqli_num_rows($result1); 
	if ($numrows1 !=0)
					{
						
							while($row=mysqli_fetch_assoc($result1))  
							{
							$mailid=$row['mailId'];
							}
					}
	
	$email=$mailid;
	echo $comp_Sts;
	$prob_observed= $_POST['Problem_Observed'];
	$process= $_POST['Rectified_by_process'];
	$person= $_POST['person'];
	$date= $_POST['date'];
	$hours= $_POST['Hours'];
	$min= $_POST['minutes'];
	$rem= $_POST['remarks'];
//	echo "Hours:".$hours."";
//	echo "Hours:".$min."";
//	echo "<BR>";
	$time = $_POST['Hours'].":". $_POST['minutes'].":00";
	$time1=strtotime($time);
	//echo $time1;
	///echo "<br>";
		


	$time2= date('H:i:s', $time1);
	//echo $time2;
	
	
	
		 $sql1 = "update complaint set 
		 Comp_Status='".$comp_Sts."',
		 Problem_Observed='".$prob_observed."',
		 Rectified_by_process ='".$process."', 
		 Rectified_by_person='".$person."',
		 RectifiedDate='".$date."',
		 RectfiedTime='".$time2."',
		 Remarks='".$rem."'
		 where serialNumber='".$sernum."'";
		 $result=mysqli_query($con,$sql1);  
		echo mysqli_error($con);
        if($result)
		{  
        echo "Data Updated Successfully";  
	//	header("location:ViewStatus.php");
		
		if($comp_Sts=="CLOSED")
		{
				try
					{
								$mail->IsSMTP(); 
								$mail->isHTML(true);
								$mail->SMTPDebug  = 0;                     
								$mail->SMTPAuth   = true;                  
								$mail->SMTPSecure = "ssl";                 
								$mail->Host       = "mail.ecil.co.in";      
								$mail->Port        = '465';             
								$mail->AddAddress($email);
								$mail->Username   =$sendermailid;  
								$mail->Password   =$senderpassword;            
								$mail->SetFrom($sendermailid,'Computer AMC');
								$mail->AddReplyTo($sendermailid,"Computer AMC");
												
								
								$mail->Subject    = $subject;
								$message = "Compliant  Ref num :".$sernum."<BR>Your complaint Rectified by process for ".$process." in PC is resolved  <br> Rectified by ".$person."  .<BR> <br>This is Autogenerated_mail from Computer  AMC  <BR>Contact Computer AMC  if not resolved.<br>
								<br></br><br></br><br></br><b><font color=#d209d9> Thanks & Regards,<br></br>Desktop Support Engineer <br>Annual Maintenance Contract (AMC) <br>ECIL.<br>Ph: 040-27182713/2734/040-27121320.</font></b>";
								
								$mail->Body  = $message;
								$mail->AltBody = $message;
								 
								if($mail->Send())
								{
							   // $msg = "Hi, Your mail successfully sent to".$email." ";
								}
								 $mail->ClearAllRecipients();
					  }
							   catch(phpmailerException $ex)
							   {
								$msg = "<div class='alert alert-warning'>".$ex->errorMessage()."</div>";
								echo 'Mailer Error: ' . $mail->ErrorInfo;
							   }

		}				/******************************************************/
			
				
		
		
        }
		else
		{  
        echo "Error in Data Updation";  
        } 

  echo '<BR><a href="http://10.19.8.13/Index.php"><font color="white">Previous page</a><br></font> 
	<a href="logout.php">LOG OUT</a>';
 ?>